name: ci

on: [push, workflow_dispatch]

env:
  npm_config_ignore_scripts: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: use npm@8
        run: npm i -g npm@8
      - name: clean install
        run: npm ci --prefer-offline
      - name: lint
        run: npm run lint
      - name: ensure formatting
        run: npm run lint:formatting
      - name: build dist
        run: npm run prepare
      - name: test
        run: npm run test:coverage
      - name: coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
