name: ci

on: [push, workflow_dispatch]

env:
  npm_config_ignore_scripts: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: use npm@8
        run: npm i -g npm@8
      - name: clean install
        run: npm ci --prefer-offline
      - name: lint
        run: npm run lint
      - name: ensure formatting
        run: npm run lint:formatting
      - name: test
        run: npm test
      - name: build dist
        run: npm run prepare
